name: PR

on: pull_request

jobs:
  ci-pr-ubuntu:
    name: "Ubuntu: verify PR builds with the most recent ponyc release"
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v4
      - name: Test with most recent ponyc release on Ubuntu
        run: |
          make test
          cd ./examples/calc
          make test

  ci-pr-windows:
    name: "Windows: verify PR builds with the most recent ponyc release"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with most recent ponyc release on Windows
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-pc-windows-msvc.zip -OutFile C:\corral.zip;
          Expand-Archive -Path C:\corral.zip -DestinationPath C:\corral;
          $env:PATH = 'C:\corral\bin;' + $env:PATH;
          .\make.ps1 -Command test 2>&1
          cd .\examples\calc
          .\make.ps1 -Command test 2>&1
